### ISSUE TITLE
Invalid JPEG data or crop window

### ISSUE THREAD

**Issue by phambao** [taki0112/BigGAN-Tensorflow#11]
I got an error when training:
Traceback (most recent call last):
  File "main.py", line 132, in <module>
    main()
  File "main.py", line 120, in main
    gan.train()
  File "/content/BigGAN-Tensorflow/BigGAN_128.py", line 302, in train
    _, summary_str, d_loss = self.sess.run([self.d_optim, self.d_sum, self.d_loss])
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py", line 956, in run
    run_metadata_ptr)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py", line 1180, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py", line 1359, in _do_run
    run_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py", line 1384, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError:  Invalid JPEG data or crop window, data size 32768
         [[{{node DecodeJpeg}}]]
         [[IteratorGetNext]]
         [[RemoteCall]]
         [[IteratorGetNext]]
Could you figure out for me? thanks

**Comment by phambao** [comment]
look like i have read the file that is not proper .jpeg
